version: "3"
services:
  server:
    container_name: server 
    build:
        context: ./server
    volumes:
      - ./server:/usr/server
      - /usr/server/node_modules
    environment:  
      - MONGO_URL=mongodb://todolistuser:@ds034348.mlab.com:34348/alvinjorrel-todo-list
      - APP_PORT=80
    ports: ['80:80'] 

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost/todos
